# -*- coding: utf-8 -*-
"""Assignment-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktKwAktqEeYORaK-al69GO8J6UHWIXsE
"""

# -*- coding: utf-8 -*-

"""Assignment-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktKwAktqEeYORaK-al69GO8J6UHWIXsE
 """

import numpy as np
import matplotlib.pyplot as plt


#if using termux
import subprocess
import shlex
#end if

#Generate line points
def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

#sides
OK=5.5
KA=4.2
AY=5.5
YO=4.2

#Generating all lines
x_OK = line_gen(O,K)
x_KA = line_gen(K,A)
x_AY = line_gen(A,Y)
x_YO = line_gen(Y,O)


#Plotting all lines
plt.plot(x_OK[0,:],x_OK[1,:],label='$OK$')
plt.plot(x_KA[0,:],x_KA[1,:],label='$KA$')
plt.plot(x_AY[0,:],x_AY[1,:],label='$AY$')
plt.plot(x_YO[0,:],x_YO[1,:],label='$YO$')

plt.plot(O[0], O[1], 'o')
plt.text(O[0] * (1 + 0.3), O[1] * (1 + 0.03) , 'O')
plt.plot(K[0], K[1], 'o')
plt.text(K[0] * (1 + 0.03), K[1] * (1 - 0.01) , 'K')
plt.plot(A[0], A[1], 'o')
plt.text(A[0] * (1), A[1] * (1) , 'A')
plt.plot(Y[0], Y[1], 'o')
plt.text(Y[0] * (1), Y[1] * (1) , 'Y')


plt.xlabel('$x$')
plt.ylabel('$y$')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')